# Generated by Django 5.0.6 on 2024-07-05 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_order'),
        ('orders', '0005_remove_order_cart_order_product_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='orders.order'),
        ),
    ]
